### ISSUE TITLE
Unique Entity ID Requirement Emphasis

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/usdr-gost#1027]
Editing the item's issue here.

**Comment by jcomeau1** [comment]
The following requirement will be imposed with the April reporting period (for Q1, 2023):

**Unique Entity ID Requirement Emphasis** – All subrecipients and contractors are required to have a Unique Entity ID (UEI) and have that number included as part of the reporting process. The UEI is the replacement for the previously used DUNS numbers, and they are issued by SAM.gov. While this requirement is not new, starting in April 2023’s P&E Report the report form will now return an error when no valid UEI is provided when creating new Subrecipient or Contractor entities. Please consult SAM.gov [here](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsam.gov%2Fcontent%2Fentity-registration&data=05%7C01%7Cjessica.martin%40obm.ohio.gov%7C3c16c5a0b4b54180629608db14556d8c%7C50f8fcc494d84f0784eb36ed57c7c8a2%7C0%7C0%7C638126129365549102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3YlxXmr501oGOndiY%2BWA5uf%2F8kmxie4q08DGdCPw2Fk%3D&reserved=0) if you have questions about obtaining a UEI.

**Comment by NatHillardUSDR** [comment]
I took a look at this a few days ago and have some questions about this - some of these are technical and some are product-facing, but I figured I'd write them out here to keep them all in one place. @trumanc  / @jcomeau1 I'd appreciate if you all could take a look and let me know your thoughts / clarifications! Happy to jump on a call as well. The questions:

a. It seems we already have UEI as a field for recipients - is this just a matter of making this a required field?
b. what are the db implications of this - is this the new primary key? Is some combination of this and other fields a the true primary key?
c. Presumably we need a migration for this?
d. what do we do for old records that don’t have a UEI - is it ok that these are now invalid?
e. what spreadsheet changes are necessary around this, and how does this interact with any required UI changes / how can we coordinate these?

**Comment by jcomeau1** [comment]
A. Yes, but it's conditional based on new subrecipients being added and only those with an entity type of subrecipient or contractor.
B. There shouldn't be any DB implications, but Truman or Andrew would be a better source to answer this.
C. No migration.
D. Old records are exempt from the requirement.
E. Currently, no Input Template changes are needed. This is strictly a validation upon upload.

**Comment by as1729** [comment]
This is necessary for March 20th deadline. We should ideally ship this by end of week so we can test this.

**Comment by NatHillardUSDR** [comment]
I have a PR for most of this now over at . 

That said, I want to make sure I'm doing the last part correctly -- 

1. What does this mean for our check against existing records? 

We currently check:
A. Is there a record with this UEI already?
B. Is there a record with this TIN already?
C. If there is both a TIN and a UEI, do they refer to the same record?

We say a record "exists" if either (1) or (2) hold. If it exists, most of the time we leave it as-is (unless the current upload owns it, in which case we update). If it doesn't exist, we create a new record.

How does this change with the new data? If I'm reading this correctly, we now want to NOT leave the record as-is if we find one, because the record will fail Treasury validation otherwise -- so if we've got a TIN match and no UEI match we update the record. This is the logic that I've implemented, but I wanted to double check

The specific scenario:
a. contractor X has TIN 123 and UEI 456
b. Looking records up by TIN (Part B above), we find that we have an existing record for contractor X -- BUT  at that time they didn't have a UEI. 
c. Since this new record references an existing subcontractor, we need to make sure that this subcontractor record has the correct 

2. What do I make of the following:

From Truman:
"What is complicated - we enforce that you have either one or the other. But in some cases now we’ll require that we have at least a UEI but maybe a TIN, but this may break uniqueness associations from the past. We need to see if this logic still holds. This is the biggest difficulty! Specifically: this only affects any NEW ones. If there is a subrecipient type subrecipient that only has a TIN from a past reporting period, this is OK."

What does this mean in practice - do I update the existing subrecipient, or leave as is and create a new record, thereby making a "conceptual" duplicate?

**Comment by jcomeau1** [comment]
From @NatHillardUSDR:
_The specific scenario:
a. contractor X has TIN 123 and UEI 456
b. Looking records up by TIN (Part B above), we find that we have an existing record for contractor X -- BUT at that time they didn't have a UEI.
c. Since this new record references an existing subcontractor, we need to make sure that this subcontractor record has the correct_

I'm not sure what you were going to say with 'c,' but the expected behavior given this scenario is that we simply allow it and not attempt to send subrecipient, **contractor x**, to Treasury. This requirement only effects new subrecipients (no previous TIN **_or_** UEI) **AND** that the subrecipient Entity Type (**Entity_type_2__c** on the Subrecipient sheet) is either "Subrecipient" or "Contractor."

Does this give you the clarity you need?

**Comment by NatHillardUSDR** [comment]
Thanks @jcomeau1 for the clarifications!

Apologies my question got cut off somehow - here’s what I originally had:

“Since this new record references an existing subcontractor, we need to make sure that this subcontractor record has the UEI set if we’re going to send it to the treasury”

Based on what you’re saying though, it sounds like the opposite is true, that we would actually in this case leave off the subcontractor entirely, even if a new record references it?

Right now if this happens we would fail the entire upload with a validation error - it sounds like we actually don’t want to do this, but if we don’t fail, and don’t update the DB, we would intentionally be omitting info from the output report with this setup - contractor X wouldn’t be included at all in the output - is this really what we want?

------------
Re: the second point, gotcha

**Comment by jcomeau1** [comment]
Yes, that's really what we want. Treasury already has the Subrecipient from prior reporting periods. If Treasury changes their mind, the partners will have to manually update the Subrecipients in the Treasury Portal; we will not include them in the bulk upload.

Just to round out the topic, it's not possible to send Subrecipient updates via the bulk load process without a Treasury assigned identifier. This identifier can only be assigned upon upload. So only new Subrecipients can be sent without the identifier. In order to get the identifier, we need to download all the Subrecipients from Treasury and then we can add them to our DB. This is the subject of this [1 Pager](https://www.notion.so/usdr/Subrecipient-ID-7c00364c7a4248ec8b618c24c3fd4e98) that has no detail yet 🤪

**Comment by NatHillardUSDR** [comment]
OK - thanks again for the clarification and for the help!

I've updated the logic and re-opened the PR over at https://github.com/usdigitalresponse/usdr-gost/pull/1105 -- I need to double check that this works with actual sheets that pass validation, but otherwise this change and associated tests should be good to go, barring feedback and any potential issues

**Comment by NatHillardUSDR** [comment]
Reopened this to address an issue Joe found in testing - https://github.com/usdigitalresponse/usdr-gost/pull/1114 has this new RP
