### ISSUE TITLE
(2)[ID] If you update the status of an "interested" grant to "Rejected", it doesn't delete itself from the Interested list.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#172]
Expected behavior - updating the status of an "Interested" grant to "Rejected" should delete itself from the interested list and show up in the Rejected list.

**Comment by CGowan44** [comment]
@mhuang-usdr Charlie mentioned this issue this morning and I also had a similar question. We both saw that when we marked a grant as interested, deleted the status, and then rejected it that it moved categories. This was when only one agency/subagency had interest in the grant. Is the grant appearing in both categories in this case because there may be one or more agencies interested in the grant with another agency rejecting it at the same time causing it to appear in both lists or is there another issue?

**Comment by mhuang-usdr** [comment]
I just looked into it again. This issue was back from when grants were getting duplicated and interested grants weren't showing up. I believe this particular one is now fixed.

I'm still seeing that interested grants aren't showing up for sub-agencies, but this might be an issue with corrupted entries in the database, so I'll wait until that is cleaned up to create another issue if needed.
