### ISSUE TITLE
"Agency" > "Team" and "Tenant" > "Organization" terminology changes

### ISSUE THREAD

**Issue by kevin-kasunic** [usdigitalresponse/usdr-gost#1846]
### Context
The goal is to provide more flexibility with how groups of users are organized on the USDR tools. Shifting from "agency" to "team" terminology will be provide this flexibility and avoid confusion for users. Similarly, while "Tenant" is not a user-facing term in the tool currently, renaming this to "Organization" provides a more clear and scalable concept to how users are organized. The scope of this ticket is specific to Grant Finder.

### Current State
- In the Grant Finder Tool, groups of users are call "agencies," and the partner that signs up (i.e. a state, city, county, non-profit, etc) is called the "tenant"

### Open Questions
- None

### Future State
- for this milestone, we will only update front end display values on grant finder for both agency and tenant.
- We will not do rename/refactor for either agency or tenant for this milestone. this means that grant finder front end will be inconsistent with the back end. Ty thinks this is okay for time being as we have a higher level conversation about whether/how arpa and grant finder codebases should be separated.

**Places where terminology updates are needed**
- [ ] My Grants tab: column headings of “Interested Agencies” → “Interested Teams” / this also needs to be updated on CVS export from My Grants
- [ ] Browse Grants tab: “Interested Agencies” → “Interested Teams” / this also needs to be updated on CVS export from My Grants
- [ ] Grant detail page (i.e. modal that displays when you click on a specific grant):
![Image](https://github.com/usdigitalresponse/usdr-gost/assets/136839582/01affcfc-1406-4dfd-aad5-930c906ea6d6)

- [ ] Dashboard tab: “Total Interested Grants by Agencies” → “Total Interested Grants by Teams”
- [ ] Dashboard tab > See all Activity > Export to CSV: column of csv file should be updated from Agency > Team
- [ ] Users tab: “Agency Name” → “Team Name”
- [ ] Users tab: “Agency Abbrv” → “Team Abbrv”
- [ ] Users tab: bulk import - csv column title should be "team name" rather than agency name
- [ ] “Agencies” tab → “Teams” tab
- [ ] Agencies tab → “Agency” title → “Team” title
- [ ] Agencies tab → Edit Agency modal → “This is used for displaying lists of agencies in compact form (e.g. in a table).” → “This is used for displaying lists of teams in compact form (e.g. in a table).”
- [ ] Agencies tab → Edit Agency modal  → “Parent Agency” → “Parent Team”
- [ ] Agencies tab → Edit Agency modal  → “Admin Delete Agency” → “Admin Delete Team.”
- [ ] Tenants tab - this tab is only visible to users who are members of the USDR tenant. The tab name and the heading on the tab should be renamed from Tenant > Organization. The header on the Tenant tab should also be renamed to "Organization"[Image](https://github.com/usdigitalresponse/usdr-gost/assets/136839582/7714092e-f7ce-4e76-80e0-82b1eabb529f)13. Add tenant modal - all instances of tenant should change to "organization" and agency to "team" (see highlighted on screenshot)
- [ ] ![Image](https://github.com/usdigitalresponse/usdr-gost/assets/136839582/66a92840-1904-48be-9785-4b0c2a8fe353)

**Note - there are a few places where we do NOT want to replace agency > team**
- on the Browse grants tab, when you open the search panel, there is a field for "Agency code" - this is actually referring to the government agency related to the grant on grants.gov, so we don't want this update to team
- this is the same for the "Agency Code" field on the top section of the grants detail page
- when setting up a new Team, there is one place that refers to ARPA's agency code- as ARPA will still be using "agency", we don't want this updated in that location.

**Comment by ed-snodgrass** [comment]
Adding this comment to help me keep track of what I've completed.

**My Grants Tab**
 - [ ] column headings of “Interested Agencies” → “Interested Teams”
 - [ ] CSV export from My Grants

**Browse Grants tab**
- [ ]  “Interested Agencies” → “Interested Teams” 
- [ ] CVS export from My Grants

**Grant detail page** (i.e. modal that displays when you click on a specific grant)
- [ ]  Agency Status -> Team Status
- [ ] "Agency" tab -> "Team" tab
- [ ] Assigned Agencies -> Assigned Teams
- [ ] "Select agencies" prompt text -> "Select teams"

**Dashboard tab**
- [ ]  See all Activity > Export to CSV: column of csv file should be updated from Agency > Team

**Users tab**
- [ ]  “Agency Name” → “Team Name”
- [ ]  “Agency Abbrv” → “Team Abbrv”
- [ ]  bulk import - csv column title should be "team name" rather than agency name

**Agencies tab**
- [ ]  “Agencies” tab → “Teams” tab
- [ ]  “Agency” title → “Team” title

**Edit Agency modal**
- [ ]  “This is used for displaying lists of agencies in compact form (e.g. in a table).” → “This is used for displaying lists of teams in compact form (e.g. in a table).”
- [ ]  “Parent Agency” → “Parent Team”
- [ ]  "Admin Delete Agency" → “Admin Delete Team.”

**Tenants tab** (this tab is only visible to users who are members of the USDR tenant.)
- [ ] Tab name "Tenant" -> "Organization"
- [ ] Tab heading "Tenant" -> "Organization"

**Add Tenant Modal**
- [ ]  Add Tenant -> Add Organization
- [ ] Tenant name is invalid -> Organization name is invalid
- [ ] Agency name -> Team name
- [ ] Agency name is invalid -> Team name is invalid
- [ ] Agency Abbrevation -> Team Abbreviation
- [ ] Agency Code -> Team Code
- [ ] Agency code is invalid -> Team code is invalid

**Comment by ed-snodgrass** [comment]
I have completed everything but the csv export pieces. Unfortunately that is dynamically creating the column headers from the field keys. The initial crack at updating those went poorly so I wonder if it is worth creating a separate ticket, or at least submitting a separate PR for these changes?

**Comment by ClaireValdivia** [comment]
@as1729 I'm not seeing this one in prod behind the profile feature flag - do you know if it was included with the prod release today, or if perhaps its behind a different feature flag?

**Comment by ClaireValdivia** [comment]
Confirmed that this is tested and working in staging! 

Only item not address that is not in another issue already is that bulk import of users - csv column still says agency name. I believe this is because it's still the actual field name, but I think could be confusing for users - created issue #2316 for this to be worked on later.
