### ISSUE TITLE
Update Saved Search default title

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2064]
### Why is this issue important?

update default Saved Search Title name

### Current State

When you create a new search, the search title default is "My Saved Search ####" - the number is a counter within the tenant, so the numbers are not very specific or meaningful to users

### Expected State

Make new search default title to be "Date - Time" when the search is created (i.e. "10/7/2023 - 3:23pm")

We don't expect the default title to automatically update after it's first created (i.e. when it's edited, the Title should not update)

### Implementation Plan

The following functions need to be added...

**Comment by adele-usdr** [comment]
![Image](https://github.com/usdigitalresponse/usdr-gost/assets/146878468/34aa4e43-ec5e-4ada-ab93-5f2c0d6a1267)

In testing a change, I saw its pretty easy to save duplicate names if you're moving quickly. Would you rather include seconds to make that less likely, or add onto the label if there's a duplicate already saved?

Also just wanted to confirm that we're not concerned about the Month/Day order here since we have a US audience.

**Comment by ClaireValdivia** [comment]
@adele-usdr  Good catch! yes, let's do seconds, as you are unable to create a search that has the same name as an existing search (you get an error message when you click to search saying its a duplicate). And yeah let's keep the month/day order for now (but fyi @caitlinwinner for awareness)

**Comment by caitlinwinner** [comment]
Seconds work! Thanks @adele-usdr
