### ISSUE TITLE
Grant Digest Email Metrics: Send emails via SES using a configuration set

### ISSUE THREAD

**Issue by TylerHendrickson** [usdigitalresponse/usdr-gost#2880]
Subtask of **[User Story: Grant Digest Email Metrics](https://github.com/usdigitalresponse/usdr-gost/issues/2749)** #2749 

#### Blocked by

- #2879
- #2996 

#### Blocks

N/A

### Definition of Done

When gost sends emails (via SES), it specifies the SES configuration set to use for email analytics.

### Implementation details

- The name of the SES configuration set will be provided by an `SES_CONFIGURATION_SET_DEFAULT` environment variable.
- This value [must be provided](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ses/command/SendEmailCommand/) as the `ConfigurationSetName` parameter [when SES `SendEmailCommand` objects are initialized](https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/src/lib/gost-aws.js#L91).

**Comment by sanason** [comment]
In light of #3035 , it appears that the implementation details for this ticket will need an additional step - some Terraform code that gives the `ECSTask` user permission to call `ses:SendEmail` on the new configuration set. Since I have very little IAM expertise, I will leave the details to @TylerHendrickson.
