### ISSUE TITLE
[ID] Error 500 in console when trying to delete an interested, rejected, or assigned grants

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#410]
Server logs show:

`Sep 28 08:49:49 AM  server: error: select "users"."id" as "user_id", "agencies"."id" as "agency_id" from "users" left join "agencies" on "users"."tenant_id" = "agencies"."tenant_id" left join "tenants" on "tenants"."id" = "users"."tenant_id" where "users"."id" = $1 and "users"."tenant_id" = $2 and "agencies"."id" = $3 - invalid input syntax for type integer: "{"0"}"`

**Comment by as1729** [comment]
@mhuang-usdr a temporary fix is up: https://www.loom.com/share/92e6392256aa4c5980743e1d8ae64eae

Since I'll be out next week it will be good for you and @TylerHendrickson to coordinate deploying this. As I mention in the video and the PR- I don't feel great about this fix since there's many things wrong in this endpoint, but I think this is the simplest way to add a test and resolve the bug for now. We should open a separate Issue to refactor this code a bit more thoroughly once I'm back from vacation.

**Comment by mhuang-usdr** [comment]
@as1729 can this be closed?

**Comment by as1729** [comment]
Yes, looks like @TylerHendrickson was able to make the necessary changes to the PR. 👍
