### ISSUE TITLE
[ID] Add anti-keywords - way to exclude certain keywords from search.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#413]
Requested by a partner

**Comment by mhuang-usdr** [comment]
Mock of what the Keywords page should look like:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/91221265/194423951-b1c5ba20-2358-4a9c-90b6-ca100f97cf67.png">

**Comment by slants3** [comment]
Taking a look at this.

It looks like we insert all keywords into a `keywords` table and then also store its functionality (to add all terms that match said keyword) and the related agency. My thinking at the moment is to continue to use this table and add new ways to interface with it to introduce anti-keywords.

It looks like there was a mass add event on 2/18 and there haven't been new keywords added since? Wanted to see if this aligns with what you expect @mhuang-usdr

**Comment by mhuang-usdr** [comment]
I don't remember a mass add event, we don't really add new keywords on our
users behalf. They usually add keywords themselves - we should have some
new ones over the last few months.

**Comment by slants3** [comment]
Ah you're totally right, I missed the latest entries!

**Comment by slants3** [comment]
Some notes...
1. Not entirely sure what the `mode` column is used for on the `keywords` table. It looks like it was used during development but discarded when real users began entering their keywords around August of last year. Looks like @Rapol was the last person to touch this as part of grantscraper
2. Is anti-keyword an intuitive name for future devs? Looks like the standard is negative keywords, though that is also slightly confusing
3. Currently debating between adding a new column to the keywords table or creating an entirely new anti-keywords table all together. Love to get input if anyone has any @TylerHendrickson @as1729

**Comment by slants3** [comment]
Looks like this should be working and is live in staging. Closing as of now.
