### ISSUE TITLE
[ID] The Browse Grants table should be sorted by Open Date by default

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#449]

**Comment by chrisxkeith** [comment]
@mhuang-usdr : I think you mean 'sorted by Open Date with most recent first'? Also, I'm assuming this doesn't affect the "My Grants" tab.

**Comment by mhuang-usdr** [comment]
@chrisxkeith you are correct on both fronts. I'll update the title to reflect that.

**Comment by chrisxkeith** [comment]
I [turned on SQL statement logging](https://github.com/usdigitalresponse/usdr-gost/wiki/How-to-turn-on-SQL-statement-logging-in-postgres) to see what sorting is being done in the database. [That SQL](https://docs.google.com/document/d/1S5FK17Z-9R7orI4SNvcPEt1eD9qywd_iZMHNXeamu7U/edit?usp=sharing) shows 'order by "created_at"', which indicates to me that the sort-by-close-date is done either in the server or client. Searching `packages/server/src` shows [one orderBy in db/index.js](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/server/src/db/index.js#L394), but I don't see that query in the Postgres log. Searching for ‘close_date’ in `packages/client/src` doesn’t show me anything that looks like code (or configuration) that would sort on that field.

**Comment by mattbroussard** [comment]
For the Browse Grants tab that this issue is about, you want the main [`getGrants`](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/server/src/db/index.js#L266) accessor and its query; it seems you are looking at two other queries that are used for other pages:

>I [turned on SQL statement logging](https://github.com/usdigitalresponse/usdr-gost/wiki/How-to-turn-on-SQL-statement-logging-in-postgres) to see what sorting is being done in the database. [That SQL](https://docs.google.com/document/d/1S5FK17Z-9R7orI4SNvcPEt1eD9qywd_iZMHNXeamu7U/edit?usp=sharing) or [this link](https://docs.google.com/document/d/1S5FK17Z-9R7orI4SNvcPEt1eD9qywd_iZMHNXeamu7U/edit?usp=sharing) shows 'order by "created_at"'

This is a different query, in `getGrantsInterested`, that feeds UI on the dashboard and recent activity pages; not the Browse Grants page.

>Searching packages/server/src shows [one orderBy in db/index.js](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/server/src/db/index.js#L394), but I don't see that query in the Postgres log

This is also a different query, in `getClosestGrants`, that is used for the dashboard and "upcoming closing dates" pages; not the Browse Grants page.

>Searching for ‘close_date’ in packages/client/src doesn’t show me anything that looks like code (or configuration) that would sort on that field.

Indeed, the Browse Grants page does not currently specify any sorting in its DB query in [`getGrants`](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/server/src/db/index.js#L266) (as [mentioned](https://usdigitalresponse.slack.com/archives/C0324KDQSCR/p1663918502362439?thread_ts=1663916754.455499&cid=C0324KDQSCR) on Slack, an `orderBy` field is [supported](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/server/src/db/index.js#L313-L328) in `getGrants`, [passed](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/server/src/routes/grants.js#L37) to it from the API endpoint (called [here](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/client/src/store/modules/grants.js#L45)), and [listed](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/client/src/components/GrantsTable.vue#L120) in GrantsTable.vue but never set to a non-empty string right now; so the query does not get an `ORDER BY` clause at all).

When an `ORDER BY` clause is not specified, SQL does not prescribe what order rows are returned in (it [sounds like](https://stackoverflow.com/a/61523507) Postgres returns rows in the order they were last updated but don't rely on this; it's undefined behavior). Indeed, when I look at this page, I don't see any apparent sorting by date:
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/3347176/195006722-d5cfbe40-20a2-4510-bb4e-364378a31e59.png">

---

I think for this task what you'll want to do is update GrantsTable.vue to properly set its [`orderBy`](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/client/src/components/GrantsTable.vue#L120) data field (both initially and when the user clicks the sort buttons) and make sure that it gets [passed](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/client/src/components/GrantsTable.vue#L222) properly through the VueX action, the [XHR to the endpoint](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/client/src/store/modules/grants.js#L45), the [call to the `getGrants` accessor](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/server/src/routes/grants.js#L37), and the [DB query](https://github.com/usdigitalresponse/usdr-gost/blob/2bfbec138d4262b054d7f11970953f58e68df29d/packages/server/src/db/index.js#L313-L32) (it looks to me like it does, but since this code path appears unused, would be good to test once you start using it with non-empty `orderBy`; also add some tests in [`grants.test.js`](https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/server/__tests__/api/grants.test.js) for this).

I think [docs on BootstrapVue's `b-table` sorting functionality](https://bootstrap-vue.org/docs/components/table#sorting) (which is purely clientside, hence currently only sorts a single page worth of rows) will be useful, particularly the part about using `.sync` to make `sort-by` a two-way binding so that you can respond to the user changing it by updating `orderBy`.

**Comment by chrisxkeith** [comment]
Thanks so much, Matt!

> so the query does not get an ORDER BY clause at all).

So I'm not completely :) crazy.

>  I don't see any apparent sorting by date

I should have looked more closely. I guess the data in my local database looks close enough to being sorted that it fooled me.

I will talk with the team on this morning's meeting to see whether I should do a quick fix for this bug (a fix which doesn't pass the sort criteria to the backend), or just close this one and go back to  https://github.com/usdigitalresponse/usdr-gost/issues/425 .

**Comment by mattbroussard** [comment]
>whether I should do a quick fix for this bug (a fix which doesn't pass the sort criteria to the backend), or just close this one and go back to https://github.com/usdigitalresponse/usdr-gost/issues/425

I don't think setting a default clientside sort for only one page of unsorted data would make any sense; I'd just do #425 based on my suggestion above (I missed that there was a separate task for that) and then this is a very small incremental change on top of that (changing the initial value of `orderBy`)

**Comment by mattbroussard** [comment]
> @chrisxkeith: I'm assuming this doesn't affect the "My Grants" tab.
> @mhuang-usdr: you are correct on both fronts. I'll update the title to reflect that.

Is there a good reason this shouldn't affect both places? Both My Grants and Browse Grants tabs share the same GrantsTable.vue component and endpoint (just with different filtering)

**Comment by chrisxkeith** [comment]
> I don't think setting a default clientside sort for only one page of unsorted data would make any sense

I agree. I'm closing this issue and will start work on [the other](https://github.com/usdigitalresponse/usdr-gost/issues/449) soon.

> Both My Grants and Browse Grants tabs share the same GrantsTable.vue component and endpoint (just with different filtering)

I'm fine with this.
