### ISSUE TITLE
(3)[ID Tool] I should be able to unmark a grant as interesting and assigned.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#54]

**Comment by Raphomet** [comment]
Just discussed this with @mhuang-usdr. There's a super low budget way of doing this that's not very pretty, but will get the job done for MVP.

The "Assigned" area already allows you to delete an assignment. It has a red trash can button. The super low budget solution is just to replicate that to the "Interested" area:

![CleanShot 2022-04-12 at 13 50 47@2x](https://user-images.githubusercontent.com/58006/163052640-12881e8f-cdf3-404d-a08c-cecae42b4a33.png)

The medium-effort way of doing this would be to improve the overall UX of this area. There are a number of minor usability issues that could be fixed with a redesign. Happy to talk through this if it's interesting, but for the sake of MVP-ability we may want to punt on that.

**Comment by Raphomet** [comment]
(Note, of course, that the red trash button should only appear on YOUR row — the table may show other agencies that are "interested")

**Comment by mhuang-usdr** [comment]
QA - LGTM

**Comment by mhuang-usdr** [comment]
There was a regression, this is no longer fixed in `prod`.

**Comment by mhuang-usdr** [comment]
Closing, superseded by #186
