### ISSUE TITLE
[ID] Reorder the grants tabs and make `My Grants` the default landing page

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#617]

**Comment by mhuang-usdr** [comment]
@cajinajr can you add a screenshot of your figma file when you get a chance?

**Comment by cajinajr** [comment]
<img width="719" alt="Screen Shot 2022-11-18 at 10 38 23 AM" src="https://user-images.githubusercontent.com/16214088/202742791-50c6dc6b-9e3b-404f-8057-8a2e652e3c7f.png">

I was experimenting with reordering the navigation tabs based on feedback from the NV partners. The aim is to reprioritize the "my grants" section over the dashboard to create a more "actionable" experience as soon as a user authenticates in. We've determined the Dashboard to be a more useful tool for the administrative user at the moment so we're moving it down the navigation line. 

Some additional context - since Rachel is consolidating keywords and eligibility codes into her redesigned search experience, we feel those tabs can go away. The Settings tab was also something I was mulling over as a catch all for tabs like Users, Agencies, and other things that could possibly come down the pipeline, like Notifications.

**Comment by mhuang-usdr** [comment]
Thanks for the context @cajinajr ! For this specific ticket, let's move `Dashboard` to after `Keywords,` and make `My Grants` the new default landing page.:

![image](https://user-images.githubusercontent.com/91221265/202814850-6e80da1e-d998-4e00-9cb0-fc3247948d23.png)

**Comment by LieAlbertTriAdrian** [comment]
@mhuang-usdr I can work on this if it's still unassigned. Here is the draft PR and the demo https://github.com/usdigitalresponse/usdr-gost/pull/788

**Comment by mhuang-usdr** [comment]
@LieAlbertTriAdrian if this is done, feel free to close it!

**Comment by mhuang-usdr** [comment]
Double-checked that this is launched on prod. Thanks @LieAlbertTriAdrian !
