### ISSUE TITLE
[ARPA] Output templates are not writing leading zeros

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#860]
- [ ]  Zip Codes
- [ ]  TIN
- [ ]  Subaward numbers

cc @trumanc @jcomeau1 who was in the meeting

**Comment by trumanc** [comment]
After investigation, it turns out that the report from the users was incorrect. There is still an issue here, but it importantly is something that is outside of the ARPA tool, and therefor not something we can fix. We should continue to educate users about how excel can cause issues with leading zeros in values that seem numeric.




The original (and incorrect) report from our user partners mentioned that certain fields that appear numeric (like the 9-digit TIN, or 5 digit ZIP code, or award numbers) have an issue when the first character of the value is a 0. Users reported that in that case, the value in the generated arpa report would omit any leading zeros, which would cause errors once they went to upload it to Treasury.


In fact, the csv files that we output from our ARPA tool DO include the leading zeros for all 3 of the fields that users reported. The problem arises when they open the file in excel, which incorrectly deduces that the fields are numeric and strips the leading zero at that point. You can confirm this by asking the user to download a fresh csv (directly from the arpa tool, never opened in excel) and then asking them to open it in a standard text editor program (notepad or textedit). In that text editor it is easy to find the value and see that it has the leading zero. 

![Image](https://user-images.githubusercontent.com/3675290/221727404-d1a29cbb-0e3c-4829-a750-ff20ff962595.png)


While excel does have some features that would ideally allow users to open csv files without accidentally removing these zeros, the format that Treasury uses for these csvs is non-standard (6 rows of completely non-standard textual information before having column headers on row 7, and data starting on row 8). Because the format is non-standard, it doesn't align with excel's parsing features and we can't rely on them. We need to educate users how they can open and edit their bulk upload csv files without running into excel issues.
