### ISSUE TITLE
[ID] Upcoming Closing Dates on dashboard don't show grants

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/usdr-gost#926]
![image](https://user-images.githubusercontent.com/3921494/217301267-09268085-b299-4018-a539-8531bceb8cb4.png)
But they do show if you click on the link:
![image](https://user-images.githubusercontent.com/3921494/217301413-99fb0e00-6e99-489f-8641-6663bdfc25fc.png)

**Comment by chrisxkeith** [comment]
Looks like the array is never filled from the database. Unclear (1) how it gets filled, and (2) why it broke in the past few days.
![image](https://user-images.githubusercontent.com/3921494/217381867-6157df3f-5452-4d12-9aff-0aa267a3a18c.png)

**Comment by as1729** [comment]
fwiw I was able to confirm that there is no difference between the production and staging network requests made from the browser.

They're both calling this endpoint `https://***.usdigitalresponse.org/api/organizations/0/grants/closestGrants/3/1`
and they're receiving data from the backend.

So the issue seems to be something to do with the front-end not setting the data correctly to this component as you seem to have identified.

I'm able to get to the point where I see that this array is empty: `grantsAndIntAgens` in `Dashboard.vue`.

I believe this commit is the culprit, but I don't know why exactly: https://github.com/usdigitalresponse/usdr-gost/commit/a311728d5d8ebc574762f83d27e07af12acdb428

Here's the prod response: 
<img width="898" alt="image" src="https://user-images.githubusercontent.com/6497366/217592121-e35952d1-6b0f-4134-bb1a-ee5090e9d3db.png">


Here's the Staging response:
<img width="751" alt="image" src="https://user-images.githubusercontent.com/6497366/217592186-ef7673ba-7ef5-46f6-9100-b08f51de758a.png">

**Comment by chrisxkeith** [comment]
Thanks for looking into this. I was afraid that it was my commit that caused the new bug. I'm going to (1) back out the change to Dashboard.vue, (2) verify that it fixes this, then (3) re-open https://github.com/usdigitalresponse/usdr-gost/issues/835 and try to fix it again.

**Comment by as1729** [comment]
@chrisxkeith I have added the suggest fix here
https://github.com/usdigitalresponse/usdr-gost/commit/a311728d5d8ebc574762f83d27e07af12acdb428#r99842151

**Comment by chrisxkeith** [comment]
Neither backing out the change, nor applying your suggested fix, fixed it.

It seems like the root of the problem is that closestGrants is an empty array (and I don't see how these changes will fix that problem).

I may start start reading the Vue documentation to figure out why [this code]( https://github.com/usdigitalresponse/usdr-gost/blob/acc5005cdd3348025974bf97664921d5509b40f5/packages/client/src/store/modules/grants.js#L53)) isn't loading closestGrants (as I think it should).

I'm also available all day today if you want to do a video chat. I need a few minutes notice, but would be happy to do that. Many, many thanks for all your help.

**Comment by as1729** [comment]
Just re-hashing our call action items here:
1. Decided to make the filters for the data in the server-side and resetting the front-end to what it used to be.
2. Adding unit tests for the server-side endpoint

Things we couldn't figure out
1. How to seed the local environment with live-looking grants data from grants.gov due to a timeout issue. This is being tracked in the slack [thread here](https://usdigitalresponse.slack.com/archives/C0324KDQSCR/p1675885071548999).

**Comment by chrisxkeith** [comment]
Duplicate of #926
