### ISSUE TITLE
Recent activity should display scrolling list

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/usdr-gost#949]
**Current State**
The query that backs this table returns every grant that has had any status set on it or has been assigned by any member of the user's team or any sub-team of the user's team. The date displayed is the last time the status was updated or an assignment was made. Despite the "Recent Activity" label, the query actually retrieves all such interactions that occurred since the beginning of time.

The pagination on this page is confusing and it is not clear what it reflects, but it does not work the same as the pagination on My Grants or Browse Grants tab.

**Expected State**
- Pagination on Recent Activity page should reflect how pagination works on Browse Grants tab
![image](https://github.com/usdigitalresponse/usdr-gost/assets/136839582/57ea1677-ba2e-4c54-9000-ab2ac13361ef)

**Comment by chrisxkeith** [comment]
???
https://github.com/usdigitalresponse/usdr-gost/blob/bd0ab6f8f53749c7590c1fd2a61ec3c99a24399c/packages/client/src/views/RecentActivity.vue#L125
https://github.com/usdigitalresponse/usdr-gost/blob/bd0ab6f8f53749c7590c1fd2a61ec3c99a24399c/packages/client/src/store/modules/dashboard.js#L78

**Comment by ClaireValdivia** [comment]
in QA party, still seeing this not working on staging and prod

**Comment by adele-usdr** [comment]
@ClaireValdivia just to make sure I'm looking at the the right issue, does anyone who saw this again have a screenshot to drop in?

**Comment by ClaireValdivia** [comment]
this is from staging, seeing similar behavior on prod
![Screenshot 2023-11-07 at 9 36 12 AM](https://github.com/usdigitalresponse/usdr-gost/assets/136839582/ac4fe066-2e8f-4c25-8809-53ae4221910b)

**Comment by adele-usdr** [comment]
@ClaireValdivia what do you expect each of those numbers to represent?  Right now, the first number is the total interested grants (which probably has more counted in it than shown on the screen), and the second is the total # shown.  I also noticed "x of y"  is a button. Is clicking on it supposed to do something?

**Comment by ClaireValdivia** [comment]
@adele-usdr I think we just want it flipped - i.e. "10 of 30", but if we are going to show it, I think there also needs to be a way to see all 30 - right now there is only the one page with 10 results. "30 of 10" should not be a button - good catch!

If this is complex, I'm wondering your thoughts on mirroring pagination on the Browse Grants table - i.e. displaying "30 recent activities" rather than the "10 of 30" and allowing pagination through them as needed.

**Comment by adele-usdr** [comment]
I don't think it's complex- I think there must've just been a different intent for this label originally. In the original screenshot that shows "9 of 4" the 9 is the count in the whole list, and 4 is the count of grants that are marked as "interested".  Maybe the interested count isn't valuable, and we should just move to a paginated list.  Or a full list with scrolling.  What should qualify as "recent"? Should it be all grants that have been viewed? All that have been marked in any way by the user?

**Comment by adele-usdr** [comment]
Reopening since we've reverted the previous fix attempt.

**Comment by ClaireValdivia** [comment]
oooh thank you for clarifying! I wonder about keeping the current way it's determining which grants show (i.e. only display activity from grants marked "Interested") but then use your idea of removing pagination and just show a scrolling list. @caitlinwinner  do you think that's a good path forward?

**Comment by caitlinwinner** [comment]
sounds good to me!

**Comment by sanason** [comment]
@ClaireValdivia @caitlinwinner 

I may be repeating earlier discussions about this ticket but I'd like to clarify what this page does now (which I can report) and what we want it to do.

The query that backs this table returns every grant that has had any status set on it or has been assigned by any member of the user's team or any sub-team of the user's team. The date displayed is the last time the status was updated or an assignment was made. Despite the "Recent Activity" label, the query actually retrieves all such interactions that occurred since the beginning of time.

As for the pagination control, I'm not sure what it was supposed to be doing originally but, at this point, I think it's just buggy.

So, one thing I could do is fix the pagination control and leave everything else as is:
<img width="1407" alt="Screenshot 2024-02-29 at 1 15 09 PM" src="https://github.com/usdigitalresponse/usdr-gost/assets/8216592/4e21098a-2901-4d3c-b321-5385c4c41f31">

If we continue to use the same query, then I feel like we might have too many items for a scrolling list. But maybe the idea was that we change the query to return just a subset of these items - just the items where the status is "Interested", for instance. Is that what we want to do?

**Comment by ClaireValdivia** [comment]
This looks great, thank you @sanason !!
